/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiPollada;

import static GuiPollada.GuiMenuPollada.modelo;
import static GuiPollada.GuiMenuPollada.tabla_ancho;
import clasesPolladas.Cliente;
import clasesPolladas.ExportarExcel;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author User
 */
public class GuiInsumos extends javax.swing.JDialog {

    /**
     * Creates new form GuiInsumos
     */
    // declaration
    public static DefaultTableModel modelo;
    private JFileChooser FileChooser = new JFileChooser();
    Vector columna = new Vector();
    Vector filas = new Vector();
    static int tabla_ancho = 0;
    static int tabla_alto = 0;
    public GuiInsumos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setMinimumSize(new Dimension(910, 730));
          btnAgregar.setMnemonic(KeyEvent.VK_A);
        this.btnEditar.setMnemonic(KeyEvent.VK_X);
        this.btnExportar.setMnemonic(KeyEvent.VK_E);
        this.btnImportar.setMnemonic(KeyEvent.VK_I);
        this.btnVolverMenu.setMnemonic(KeyEvent.VK_M);
        this.btnLimpiar.setMnemonic(KeyEvent.VK_L);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantKilosPollos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreciokilosPollos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantKilosPapas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioKilosPapas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCostoCondimentos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCostoLechuga = new javax.swing.JTextField();
        txtCostoLimon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCostoAji = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCostoAceite = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTreporte = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("INSUMOS:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 190, 42);

        jLabel2.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Cantidad Kilos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 90, 140, 24);

        jLabel3.setFont(new java.awt.Font("Marion", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("POLLOS:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 40, 144, 37);

        txtCantKilosPollos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantKilosPollosKeyPressed(evt);
            }
        });
        getContentPane().add(txtCantKilosPollos);
        txtCantKilosPollos.setBounds(340, 90, 50, 30);

        jLabel4.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("Precio Por Kilo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 150, 137, 24);

        txtPreciokilosPollos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPreciokilosPollosKeyPressed(evt);
            }
        });
        getContentPane().add(txtPreciokilosPollos);
        txtPreciokilosPollos.setBounds(340, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Marion", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("PAPAS:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 50, 144, 37);

        jLabel6.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("Cantidad Kilos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 100, 133, 24);

        txtCantKilosPapas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantKilosPapasKeyPressed(evt);
            }
        });
        getContentPane().add(txtCantKilosPapas);
        txtCantKilosPapas.setBounds(690, 100, 50, 30);

        jLabel7.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("Precio Por Kilo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 160, 137, 24);

        txtPrecioKilosPapas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKilosPapasKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrecioKilosPapas);
        txtPrecioKilosPapas.setBounds(690, 150, 50, 30);

        jLabel8.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 180, 806, 20);

        txtCostoCondimentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoCondimentosKeyPressed(evt);
            }
        });
        getContentPane().add(txtCostoCondimentos);
        txtCostoCondimentos.setBounds(340, 210, 50, 36);

        jLabel9.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("Costo Condimentos :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 210, 185, 24);

        jLabel10.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("Costo Lehuga :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 210, 133, 24);

        txtCostoLechuga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoLechugaKeyPressed(evt);
            }
        });
        getContentPane().add(txtCostoLechuga);
        txtCostoLechuga.setBounds(690, 200, 50, 36);

        txtCostoLimon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoLimonKeyPressed(evt);
            }
        });
        getContentPane().add(txtCostoLimon);
        txtCostoLimon.setBounds(340, 260, 50, 36);

        jLabel11.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Costo Limon :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 260, 123, 24);

        txtCostoAji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoAjiKeyPressed(evt);
            }
        });
        getContentPane().add(txtCostoAji);
        txtCostoAji.setBounds(690, 250, 50, 30);

        jLabel12.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setText("Costo Aji :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(550, 250, 91, 24);
        getContentPane().add(txtCostoAceite);
        txtCostoAceite.setBounds(690, 290, 50, 30);

        jLabel13.setFont(new java.awt.Font("Marion", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 102));
        jLabel13.setText("Costo Aceite:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(540, 290, 119, 24);

        JTreporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KILOS POLLOS", "PRECIO POR KILO", "TOTAL ", "KILOS PAPA", "PRECIO POR KILO", "TOTAL", "CONDIMENTOS", "ACEITE", "LIMON", "AJI", "LECHUGA", "INVERSION TOTAL"
            }
        ));
        JTreporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTreporte);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 410, 850, 110);

        btnAgregar.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(90, 350, 140, 40);

        btnExportar.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnExportar.setText("EXPORTAR");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar);
        btnExportar.setBounds(90, 640, 160, 40);

        jLabel15.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 320, 779, 14);

        btnEditar.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(340, 350, 140, 40);

        btnLimpiar.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(590, 350, 180, 40);

        btnImportar.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnImportar.setText("IMPORTAR");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnImportar);
        btnImportar.setBounds(360, 640, 150, 40);

        btnVolverMenu.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnVolverMenu.setText("VOLVER A MENU");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenu);
        btnVolverMenu.setBounds(590, 640, 220, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Excel-icon.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 540, 100, 90);

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel19.setText("Diseñado por: Ing. Juan Alexander Carranza Alarcón  Cell: 993938955");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(210, 10, 560, 21);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/document-excel-icon.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(380, 540, 100, 90);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/back-icon-1.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(650, 530, 100, 100);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Pollada\\src\\fotos\\Colorful-lines-stripes-rays-color-rainbow_2560x1600.jpg")); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Cliente c = new Cliente(Double.parseDouble(txtCantKilosPollos.getText()), Double.parseDouble(txtPreciokilosPollos.getText()),
                Double.parseDouble(txtCantKilosPapas.getText()), Double.parseDouble(txtPrecioKilosPapas.getText()),
                Double.parseDouble(txtCostoCondimentos.getText()), Double.parseDouble(txtCostoLechuga.getText()),
                Double.parseDouble(txtCostoLimon.getText()), Double.parseDouble(txtCostoAji.getText()),
                Double.parseDouble(txtCostoAceite.getText()));

        DefaultTableModel modelo;
        modelo = (DefaultTableModel) this.JTreporte.getModel();

        Object fila[] = new Object[12];

        fila[0] = String.valueOf(c.getDoubCantidadKiloPollo());
        fila[1] = String.valueOf(c.getDoubPrecioKiloPollo());
        fila[2] = String.valueOf(c.totalPollos());
        fila[3] = String.valueOf(c.getDoubCantidadKiloPapa());
        fila[4] = String.valueOf(c.getDoubPrecioKiloPapa());
        fila[5] = String.valueOf(c.totalPapas());
        fila[6] = String.valueOf(c.getDoubCostoCondimentos());
        fila[7] = String.valueOf(c.getDoubCostoAceite());
        fila[8] = String.valueOf(c.getDoubCostoLimon());
        fila[9] = String.valueOf(c.getDoubCostoLechuga());
        fila[10] = String.valueOf(c.getDoubCostoAji());
        fila[11] = String.valueOf(c.inversionTotal());

        modelo.addRow(fila);
        this.JTreporte.setModel(modelo);

        // borrado de cajas 
        this.txtCantKilosPapas.setText("");
        this.txtPreciokilosPollos.setText("");
        this.txtPrecioKilosPapas.setText("");
        this.txtCantKilosPollos.setText("");
        this.txtCostoAceite.setText("");
        this.txtCostoAji.setText("");
        this.txtCostoCondimentos.setText("");
        this.txtCostoLechuga.setText("");
        this.txtCostoLimon.setText("");
        this.txtPrecioKilosPapas.setText("");
        this.txtPreciokilosPollos.setText("");
        
        // this is to point out the cursor again into the first box
        this.txtCantKilosPollos.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void JTreporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreporteMouseClicked
        // TODO add your handling code here:
        int i = this.JTreporte.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.JTreporte.getModel();
        this.txtCantKilosPollos.setText(model.getValueAt(i, 0).toString());
        this.txtPreciokilosPollos.setText(model.getValueAt(i, 1).toString());
        this.txtCantKilosPapas.setText(model.getValueAt(i, 3).toString());
        this.txtPrecioKilosPapas.setText(model.getValueAt(i, 4).toString());
        this.txtCostoCondimentos.setText(model.getValueAt(i, 6).toString());
        this.txtCostoAceite.setText(model.getValueAt(i, 7).toString());
        this.txtCostoLimon.setText(model.getValueAt(i, 8).toString());
        this.txtCostoAji.setText(model.getValueAt(i, 9).toString());
        this.txtCostoLechuga.setText(model.getValueAt(i, 10).toString());
    }//GEN-LAST:event_JTreporteMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        int i = this.JTreporte.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) this.JTreporte.getModel();
        // la logica de la pollada 
        double cantKilosPollos = Double.parseDouble(this.txtCantKilosPollos.getText());
        double precPorKiloPollos = Double.parseDouble(this.txtPreciokilosPollos.getText());
        double cantKilosPapas = Double.parseDouble(this.txtCantKilosPapas.getText());
        double precPorKilosPapas = Double.parseDouble(this.txtPrecioKilosPapas.getText());
        double condimentos = Double.parseDouble(this.txtCostoCondimentos.getText());
        double aceite = Double.parseDouble(this.txtCostoAceite.getText());
        double limon = Double.parseDouble(this.txtCostoLimon.getText());
        double aji = Double.parseDouble(this.txtCostoAji.getText());
        double lechuga = Double.parseDouble(this.txtCostoLechuga.getText());
        //precio total
        double totalPollo;
        totalPollo = cantKilosPollos * precPorKiloPollos;

        double totalPapa;
        totalPapa = cantKilosPapas * precPorKilosPapas;

        double totalInversion;
        totalInversion = totalPollo + totalPapa + condimentos + aceite + aji + limon + lechuga;
        // get value 
        
        if (i >= 0) {

            model.setValueAt(String.valueOf(cantKilosPollos), i, 0);
            model.setValueAt(String.valueOf(precPorKiloPollos), i, 1);
            model.setValueAt(String.valueOf(totalPollo), i, 2);
            model.setValueAt(String.valueOf(cantKilosPapas), i, 3);
            model.setValueAt(String.valueOf(precPorKilosPapas), i, 4);
            model.setValueAt(String.valueOf(totalPapa), i, 5);
            model.setValueAt(String.valueOf(condimentos), i, 6);
            model.setValueAt(String.valueOf(aceite), i, 7);
            model.setValueAt(String.valueOf(limon), i, 8);
            model.setValueAt(String.valueOf(aji), i, 9);
            model.setValueAt(String.valueOf(lechuga), i, 10);
            model.setValueAt(String.valueOf(totalInversion), i, 11);

        } else {
            JOptionPane.showMessageDialog(null, "UPDATE ERROR");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.txtCantKilosPapas.setText("");
        this.txtPreciokilosPollos.setText("");
        this.txtPrecioKilosPapas.setText("");
        this.txtCantKilosPollos.setText("");
        this.txtCostoAceite.setText("");
        this.txtCostoAji.setText("");
        this.txtCostoCondimentos.setText("");
        this.txtCostoLechuga.setText("");
        this.txtCostoLimon.setText("");
        this.txtPrecioKilosPapas.setText("");
        this.txtPreciokilosPollos.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed

        if (this.JTreporte.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);

            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<JTable>();
                List<String> nom = new ArrayList<String>();
                tb.add(this.JTreporte);
                nom.add("Compras por factura");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    ExportarExcel e = new ExportarExcel(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel en el directorio seleccionado", "Mensaje de Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos para exportar", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
        }

        // borrando la jTable
        // getModel() = This method returns information on the current data model during the processing of a personalized reverse engineering.
        // The list of available data is described in the pPropertyName values table.
        DefaultTableModel dm = (DefaultTableModel) this.JTreporte.getModel();
        for (int i = dm.getRowCount() - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
        FileChooser.showDialog(null, "Importar Hoja ");
        File file = FileChooser.getSelectedFile();
        if (!file.getName().endsWith("xls")) {

            JOptionPane.showMessageDialog(null, "Seleccione un archivo excel...", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                CrearTabla(file);
            } catch (IOException ex) {
                Logger.getLogger(GuiMenuPollada.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelo = new DefaultTableModel(filas, columna);
            tabla_ancho = modelo.getColumnCount() * 125;
            tabla_alto = modelo.getRowCount() * 50;
            JTreporte.setPreferredSize(new Dimension(tabla_ancho, tabla_alto));
            JTreporte.setModel(modelo);
        }


    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        this.setVisible(false);
        GuiMenuPollada g = new GuiMenuPollada();
        g.setVisible(true);
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void txtCantKilosPollosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKilosPollosKeyPressed
        // TODO add your handling code here:
           if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtPreciokilosPollos.requestFocus();
    }//GEN-LAST:event_txtCantKilosPollosKeyPressed

    private void txtPreciokilosPollosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreciokilosPollosKeyPressed
        // TODO add your handling code here:
           if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCantKilosPapas.requestFocus();
    }//GEN-LAST:event_txtPreciokilosPollosKeyPressed

    private void txtCantKilosPapasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKilosPapasKeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtPrecioKilosPapas.requestFocus();
        
    }//GEN-LAST:event_txtCantKilosPapasKeyPressed

    private void txtPrecioKilosPapasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKilosPapasKeyPressed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCostoCondimentos.requestFocus();
    }//GEN-LAST:event_txtPrecioKilosPapasKeyPressed

    private void txtCostoCondimentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoCondimentosKeyPressed
        // TODO add your handling code here:
         if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCostoLimon.requestFocus();
    }//GEN-LAST:event_txtCostoCondimentosKeyPressed

    private void txtCostoLimonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoLimonKeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCostoLechuga.requestFocus();
    }//GEN-LAST:event_txtCostoLimonKeyPressed

    private void txtCostoLechugaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoLechugaKeyPressed
        // TODO add your handling code here:
           if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCostoAji.requestFocus();
    }//GEN-LAST:event_txtCostoLechugaKeyPressed

    private void txtCostoAjiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoAjiKeyPressed
        // TODO add your handling code here:
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtCostoAceite.requestFocus();
    }//GEN-LAST:event_txtCostoAjiKeyPressed

    /// metodo para crear tabla ... 
    public void CrearTabla(File file) throws IOException {

        Workbook workbook = null;

        try {
            workbook = Workbook.getWorkbook(file);

            Sheet sheet = workbook.getSheet(0);
            columna.clear();

            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                columna.add(cell1.getContents());
            }
            filas.clear();

            for (int j = 1; j < sheet.getRows(); j++) {

                Vector d = new Vector();

                for (int i = 0; i < sheet.getColumns(); i++) {

                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                filas.add(d);
            }

        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiInsumos dialog = new GuiInsumos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTreporte;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantKilosPapas;
    private javax.swing.JTextField txtCantKilosPollos;
    private javax.swing.JTextField txtCostoAceite;
    private javax.swing.JTextField txtCostoAji;
    private javax.swing.JTextField txtCostoCondimentos;
    private javax.swing.JTextField txtCostoLechuga;
    private javax.swing.JTextField txtCostoLimon;
    private javax.swing.JTextField txtPrecioKilosPapas;
    private javax.swing.JTextField txtPreciokilosPollos;
    // End of variables declaration//GEN-END:variables
}
